openapi: 3.0.0
x-stoplight:
  id: 5fs0in4eyuypa
info:
  version: '1.1'
  title: 'OpenAPI Specification: Products API'
  description: This specification describes the Products API of the Zalando Merchant Platform.
  x-audience: external-merchant
  x-api-id: 49e51b92-1b36-447f-adb1-be1305faaea6
paths:
  '/merchants/{merchant_id}/products/identifiers/{ean}':
    put:
      tags:
        - Product Association
      summary: |
        Creates a new simple already known by Zalando by registering the Merchant identifiers in the Zalando system.
      parameters:
        - $ref: '#/components/parameters/merchant_id'
        - $ref: '#/components/parameters/ean'
      requestBody:
        $ref: '#/components/requestBodies/ProductAssociationBody'
      responses:
        '204':
          description: |
            Your sku is successfully associated with the existing product
        '400':
          $ref: '#/components/responses/InvalidBodyError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
        default:
          $ref: '#/components/responses/GenericError'
      security:
        - {}
      x-stoplight:
        id: 6v78is3ikqvd8
  '/products/identifiers/{ean}':
    get:
      tags:
        - Discovery API
      summary: |
        Look up the existing product details in Zalando platform
      parameters:
        - $ref: '#/components/parameters/ean'
      responses:
        '200':
          $ref: '#/components/responses/LookUpResponse'
        '409':
          $ref: '#/components/responses/ConflictError'
        default:
          $ref: '#/components/responses/GenericError'
      security:
        - {}
      x-stoplight:
        id: kmajv3plc7p8s
components:
  parameters:
    ean:
      name: ean
      in: path
      description: The International Article Number or also known as European Article Number
      required: true
      schema:
        $ref: '#/components/schemas/EAN'
    merchant_id:
      name: merchant_id
      in: path
      description: Id of the merchant
      required: true
      schema:
        type: string
        format: string
    merchant-simple-id:
      name: merchant-simple-id
      in: path
      description: Merchant simple identifier
      required: true
      schema:
        type: string
        format: string
  requestBodies:
    ProductAssociationBody:
      description: Information of the product to associate with
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductAssociationSchema'
  securitySchemes:
    merchant_platform:
      type: oauth2
      description: The Products service uses the OpenID Connect (OIDC) authentication layer of OAuth 2 to handle the client credentials process flow.
      flows:
        clientCredentials:
          scopes:
            products/read: scope to read a product
            products/write: scope to create or update a product
          tokenUrl: 'https://api-sandbox.merchants.zalando.com/auth/token'
  responses:
    ConflictError:
      description: 'The request is semantically correct, but it cannot be processed due to business reasons. e.g. A product with same id was already submitted. Please refer to the response.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    InvalidBodyError:
      description: No product with the given EAN could be found for this merchant
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    ForbiddenError:
      description: Accessing the data you were trying to reach is forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    NotFoundError:
      description: No product with the given EAN could be found for this merchant
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    TooManyRequestsError:
      description: 'Too Many Requests. Server busy, please retry later.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    GenericError:
      description: Error occurred - see status code and problem object for more information.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    LookUpResponse:
      description: |
        Successfully looked up product detail information
      content:
        application/json;charset=utf-8:
          schema:
            $ref: '#/components/schemas/LookUp'
  schemas:
    EAN:
      type: string
      description: The International Article Number or also known as European Article Number
      example: '9780679762881'
      x-stoplight:
        id: yllc68otkoio6
    ProductAssociationSchema:
      type: object
      description: Information of the product to associate with
      properties:
        merchant_product_simple_id:
          $ref: '#/components/schemas/MerchantProductId'
        merchant_product_config_id:
          $ref: '#/components/schemas/MerchantConfigId'
        merchant_product_model_id:
          $ref: '#/components/schemas/MerchantModelId'
      required:
        - merchant_product_simple_id
      x-stoplight:
        id: 8wsnjtanspvf1
    MerchantProductId:
      type: string
      description: |
        Merchant product simple identifier. Simples is a bottom level tier of a product, contains sizes, metrics, etc.
      example: ED-7-09349-5443-L
      x-stoplight:
        id: oxkdctrhcdjxj
    MerchantConfigId:
      type: string
      description: |
        Merchant product config identifier. Config is a second tier of a product, contains colors, materials, etc.
      example: A213-1232SF-SDG62G-213G
      x-stoplight:
        id: q2cdy3619nyka
    MerchantModelId:
      type: string
      description: |
        Merchant product model identifier. Model is a top level tier of a product, contains target age groups, brand, size charts, etc.
      example: MODEL-ID-ABC
      x-stoplight:
        id: phwtf0alswtjl
    Problem:
      type: object
      properties:
        type:
          type: string
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          format: uri
          default: 'about:blank'
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in English and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized);
        status:
          type: integer
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          format: int32
          minimum: 100
          exclusiveMaximum: true
          maximum: 600
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
        instance:
          type: string
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
      example:
        type: 'https://zalando.github.io/problem/constraint-violation'
        title: Service Unavailable
        status: 503
        detail: Connection to database timed out
      x-stoplight:
        id: 5k5mdmgxvbpr3
    LookUp:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              ean:
                $ref: '#/components/schemas/EAN'
      example:
        items:
          - ean: '9780679762881'
      x-stoplight:
        id: c80vaxi2bbvxt
